### ISSUE TITLE
Native rolls not working with V11 Foundry and DND 2.3.0

### ISSUE THREAD

**Issue by DesertEagle50** [kakaroto/Beyond20#1082]
**Describe the bug**
Beyond20 native rolls do not show up on the VTT.

**To Reproduce**
Enable native rolls 
roll anything in beyond20

console error message:
beyond20.js:71 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'override')
    at Beyond20.createActorData (beyond20.js:71:52)
    at Beyond20.getUpdatedActor (beyond20.js:8:38)
    at Beyond20.rollItems (beyond20.js:624:34)
    at Beyond20.handleBeyond20Request (beyond20.js:657:30)
    at Object.fn (beyond20.js:768:59)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at handleRoll (fvtt_script.js:4073:35)
    at HTMLDocument.event (fvtt_script.js:102:9)
    
Foundry Virtual Tabletop: Version 11 Stable, 11.307
Game System: dnd5e, 2.3.0

**Comment by cahudson94** [comment]
Can confirm this happens with both Firefox and Chrome and for my case is a change from Foundry Version 10 - 11.

**Comment by Aeristoka** [comment]
> Can confirm this happens with both Firefox and Chrome and for my case is a change from Foundry Version 10 - 11.

Did you change dnd5e version at the same time?

**Comment by cahudson94** [comment]
> > Can confirm this happens with both Firefox and Chrome and for my case is a change from Foundry Version 10 - 11.
> 
> Did you change dnd5e version at the same time?

Not initially, I can try to downgrade and see if that helps.

**Comment by Aeristoka** [comment]
> > > Can confirm this happens with both Firefox and Chrome and for my case is a change from Foundry Version 10 - 11.
> > 
> > 
> > Did you change dnd5e version at the same time?
> 
> Not initially, I can try to downgrade and see if that helps.

Might be worth a try, there was some question as to if it was actually the dnd5e system changing something that broke things.

**Comment by cahudson94** [comment]
> > Can confirm this happens with both Firefox and Chrome and for my case is a change from Foundry Version 10 - 11.
> 
> Did you change dnd5e version at the same time?

Not initially, I can try to downgrade and see if that helps.

**Comment by anakreon** [comment]
I'm getting a similar error after upgrading Foundry from 10 to 11 and dnd5e 2.3.1. When trying to roll in DnDBeyond, I get `Cannot read properties of undefined (reading '0')` in Foundry.
Did downgrading anything help?

**Comment by runegri** [comment]
Hi.
I've been seeing the same error after upgrading to Foundry v11-latest and the latest dnd5e system. I tried to downgrade dnd5e to v2.2.2 but I am still seeing the same error. 

My chrome log says the following:
`foundry.js:68202 Cannot read properties of undefined (reading '0')`
and then it follows up with
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at Tokenizer.stateBeforeEntity (home/rune/Foundry/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:584:47)
    at Tokenizer.parse (home/rune/Foundry/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:848:26)
    at Tokenizer.write (home/rune/Foundry/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:159:14)
    at Parser.write (home/rune/Foundry/resources/app/node_modules/htmlparser2/lib/Parser.js:459:28)
    at sanitizeHtml (home/rune/Foundry/resources/app/node_modules/sanitize-html/index.js:588:10)
    at cleanHTML (/home/rune/Foundry/resources/app/dist/database/validators.mjs:1:233)
    at HTMLField.sanitizeHTMLField [as sanitize] (/home/rune/Foundry/resources/app/dist/database/sanitization.mjs:1:1235)
    at ChatMessage._sanitizeFields (/home/rune/Foundry/resources/app/dist/database/backend/server-document.mjs:1:7729)
    at ChatMessage.sanitizeUserInput (/home/rune/Foundry/resources/app/dist/database/backend/server-document.mjs:1:7436)
    at ServerDatabaseBackend._createDocuments (/home/rune/Foundry/resources/app/dist/database/backend/server-backend.mjs:1:2611)
```

**Comment by dmportella** [comment]
Anyone here still getting this issue?

**Comment by DesertEagle50** [comment]
Just tried it right now. Doesn't work. get this error on a Strength save:

Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'str')
[Detected 1 package: beyond20(1.5.5)]
    at Beyond20.createActorData (beyond20.js:55:53)
    at Beyond20.getUpdatedActor (beyond20.js:8:38)
    at Beyond20.rollSavingThrow (beyond20.js:553:34)
    at Beyond20.handleBeyond20Request (beyond20.js:648:30)
    at Object.fn (beyond20.js:779:59)
    at #call (foundry.mjs:23832:20)
    at Hooks.call (foundry.mjs:23815:40)
    at handleRoll (fvtt_script.js:4626:35)
    at HTMLDocument.event (fvtt_script.js:110:9)
