### ISSUE TITLE
Encounter tracker crashes when switching between some stat blocks when either stat block feature is set

### ISSUE THREAD

**Issue by jaypoulz** [kakaroto/Beyond20#827]
How to reproduce:
1. Go to the encounter builder
2. Add a young silver dragon
3. Add a war priest
4. Create the encounter

Now, ensure either a) replace dices formulas or b) add roll buttons to stat boxes are set

5. Run the encounter (optional) and switch between the two monsters. After you've selected each stat block once, the next switch will crash the tracker.

The console log reads:
```
index.js:4375 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Mi (https://media.dndbeyond.com/encounter-builder/static/js/2.71003273.chunk.js:1:10566754)
    at https://media.dndbeyond.com/encounter-builder/static/js/2.71003273.chunk.js:1:10580027
    at exports.unstable_runWithPriority (https://media.dndbeyond.com/encounter-builder/static/js/2.71003273.chunk.js:1:10600919)
    at cg (https://media.dndbeyond.com/encounter-builder/static/js/2.71003273.chunk.js:1:10524999)
    at Jj (https://media.dndbeyond.com/encounter-builder/static/js/2.71003273.chunk.js:1:10577932)
    at yj (https://media.dndbeyond.com/encounter-builder/static/js/2.71003273.chunk.js:1:10574116)
    at https://media.dndbeyond.com/encounter-builder/static/js/2.71003273.chunk.js:1:10525289
    at exports.unstable_runWithPriority (https://media.dndbeyond.com/encounter-builder/static/js/2.71003273.chunk.js:1:10600919)
    at cg (https://media.dndbeyond.com/encounter-builder/static/js/2.71003273.chunk.js:1:10524999)
    at fg (https://media.dndbeyond.com/encounter-builder/static/js/2.71003273.chunk.js:1:10525235)
    at gg (https://media.dndbeyond.com/encounter-builder/static/js/2.71003273.chunk.js:1:10525170)
    at Ga (https://media.dndbeyond.com/encounter-builder/static/js/2.71003273.chunk.js:1:10594385)
    at https://media.dndbeyond.com/encounter-builder/static/js/2.71003273.chunk.js:1:10502505
    at HTMLDocument.sentryWrapped (https://media.dndbeyond.com/encounter-builder/static/js/2.71003273.chunk.js:1:6726714)
```

I haven't noticed this with all monsters, but it is reproducible with certain monsters - like the ones mentioned above. I suspect the DOM manipulation done but the beyond20 extension is not fully compatible with the DOM manipulation done by D&DB.

**Comment by jaypoulz** [comment]
@Aeristoka Missed that issue when looking for duplicates.

One thing to note those - both monsters I selected are *not* homebrew.

**Comment by Aeristoka** [comment]
> @Aeristoka Missed that issue when looking for duplicates.
> 
> One thing to note those - both monsters I selected are _not_ homebrew.

Yep, we know. KaKaRoTo has the issue filed with DnDBeyond.

What they SHOULD do immediately is give us a toggle to disable Digital Dice on Monsters, because not everybody wants that (and it would avoid this issue).

**Comment by jaypoulz** [comment]
@Aeristoka excellent - thanks for the follow up
